version: '3.3'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "frontend-DNC-angular"
    volumes:
      - ./events/src:/root/app/events/src
    ports:
      - "4200:4200"
    network_mode: "host"
    restart: always
    working_dir: /root/app/events
    command: >
      sh -c "ng serve --host 0.0.0.0"

