version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: "backend-DNC-python"
    volumes:
      - ./:/root/app
    ports:
      - "8000:8000"
    network_mode: "host"
    restart: always
    working_dir: /root/app/dnc
    # network_mode: "host"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

