# Generated by Django 2.1.7 on 2019-02-26 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('start_date', models.TextField(blank=True, null=True)),
                ('end_date', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('official', models.BooleanField(blank=True, null=True)),
                ('visibility', models.TextField(blank=True, null=True)),
                ('guests_can_invite_others', models.BooleanField(blank=True, null=True)),
                ('modified_date', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
                ('participant_count', models.TextField(blank=True, null=True)),
                ('reason_for_private', models.TextField(blank=True, null=True)),
                ('order_email_template', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'events',
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('contact_phone', models.TextField(blank=True, null=True)),
                ('primary', models.BooleanField(blank=True, null=True)),
                ('contact_email', models.TextField(blank=True, null=True)),
                ('contact_family_name', models.TextField(blank=True, null=True)),
                ('contact_given_name', models.TextField(blank=True, null=True)),
                ('host_given_name', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('address_type', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('accuracy', models.TextField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('postal_code', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('modified_date', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
                ('number_spaces_remaining', models.TextField(blank=True, null=True)),
                ('spaces_remaining', models.BooleanField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='members',
            field=models.ManyToManyField(through='events.RSVP', to=settings.AUTH_USER_MODEL),
        ),
    ]
