# Generated by Django 2.1.7 on 2019-02-26 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='members',
            new_name='rsvped_users',
        ),
    ]
