# Generated by Django 2.1.7 on 2019-02-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190226_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='rsvped_users',
            new_name='users',
        ),
    ]
